rsat:
  _target_: tinycmax.loss.cmax.RatioSquaredAvgTimestamps
  accumulation_window: ${...train.cmax.accumulation_window}  # same as cmax
  base: ${.accumulation_window}
  warp: ${...train.cmax.warp}
